### ISSUE TITLE
store volume size in volume info

### ISSUE THREAD

**Issue by Madhu-1** [gluster/glusterd2#1081]
return volume size in volume create and volume list response.

**Comment by prashanthpai** [comment]
How would you figure the size ?

**Comment by aravindavk** [comment]
- Auto provisioned volumes will have size info in request, that needs to be stored in Volinfo.
- Manual provisioned volumes need to fetch brick sizes during volume create, calculate volume size and update the volume size in volinfo.

Update also needed during expand/shrink.

For GCS we can skip the manual provisioned volumes, since CSI will use the auto provisioned volumes.

**Comment by prashanthpai** [comment]
> For GCS we can skip the manual provisioned volumes, since CSI will use the auto provisioned volumes.

Sounds like a good plan :+1:

**Comment by aravindavk** [comment]
This PR adds Volume capacity for auto provisioned volumes. Closing this issue now, please open new issue if Volume size is required for manual provisioned volumes as well https://github.com/gluster/glusterd2/pull/1193
