### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by kshlm** [gluster/glusterd2#205]
We need to provide a CLI application for managing Gluster. The CLI app will be a consumer of the ReST API.

**Comment by aravindavk** [comment]
Since `glusterd2` CLI is now REST client, it can be used to manage or get information from multiple Clusters.

User/Auth management part is TBD. We may have to add `.env` or additional parameter for CLI command to accept Username and Secret

For Example(TBD - This will change depending on Auth we support):

    gluster -h <HOST> -u <USERNAME> -p <SECRET>  # This opens gluster shell `gluster>`
    gluster -h <HOST> -u <USERNAME>              # This prompts for Secret and then opens gluster shell
    gluster -h <HOST> -u <USERNAME> -p <SECRET> <CMD> <ARGS> # Same as `glusterd1` CLI but additionally takes HOST, USERNAME and SECRET parameters

We should take this opportunity to fix/improve some of the issues we currently face with existing CLI commands.

- In `glusterd1` optional arguments are parsed as positional arguments, we should change this in `glusterd2`. For example, in volume create command Use `--replica 2` instead of `replica 2`. This eliminates lot of parsing overhead and bugs during parsing.
- Split force argument into meaningful flags. For Example, `--allow-root-dir`, `--reuse-bricks` during Volume Create(REST APIs should be enhanced to make this work)
- Depricate XML output and support JSON?
- Which is better? `volume info` or `volume-info`(First option may need extra work to parse arguments, for second option can take advantage of existing parsing library)

Please add if any other things to consider while designing `glusterd2` CLIs.

**Comment by kshlm** [comment]
Going from first to last in the bullets

- +1 from me. This makes it easier to parse flags for each command.
- +1
- As the rest api itself provides JSON, cli should only need to provide the
raw responses if requested.
- there are packages that provide this behaviour. So we should be okay with
'gluster volume info' style of commands.


On 28 Dec 2016 15:21, "Aravinda VK" <notifications@github.com> wrote:

Since glusterd2 CLI is now REST client, it can be used to manage or get
information from multiple Clusters.

User/Auth management part is TBD. We may have to add .env or additional
parameter for CLI command to accept Username and Secret

For Example(TBD - This will change depending on Auth we support):

gluster -h <HOST> -u <USERNAME> -p <SECRET>  # This opens gluster
shell `gluster>`
gluster -h <HOST> -u <USERNAME>              # This prompts for Secret
and then opens gluster shell
gluster -h <HOST> -u <USERNAME> -p <SECRET> <CMD> <ARGS> # Same as
`glusterd1` CLI but additionally takes HOST, USERNAME and SECRET
parameters

We should take this opportunity to fix/improve some of the issues we
currently face with existing CLI commands.

   - In glusterd1 optional arguments are parsed as positional arguments, we
   should change this in glusterd2. For example, in volume create command
   Use --replica 2 instead of replica 2. This eliminates lot of parsing
   overhead and bugs during parsing.
   - Split force argument into meaningful flags. For Example,
   --allow-root-dir, --reuse-bricks during Volume Create(REST APIs should
   be enhanced to make this work)
   - Depricate XML output and support JSON?
   - Which is better? volume info or volume-info(First option may need
   extra work to parse arguments, for second option can take advantage of
   existing parsing library)

Please add if any other things to consider while designing glusterd2 CLIs.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gluster/glusterd2/issues/205#issuecomment-269453556>,
or mute the thread

**Comment by kshlm** [comment]
Need a simple CLI that just works for Rouge One. We can think/worry about auth stuff later.

**Comment by aravindavk** [comment]
Summarized the approach required for designing the CLI for Glusterd2. 

**Note:** Support can be added for backward incompatible changes by providing `-l` or `--legacy` option. Retaining same XML output may requires lot of work.

To run Gluster CLI inside Cluster, Authentication can be controlled
using `iptables`(or any other tool) without creating users in glusterd2.

For example, Glusterd2 REST API port is 24007

    iptables -I OUTPUT -p tcp --dport 24007 -j REJECT
    iptables -I OUTPUT -p tcp --dport 24007 --match owner --gid-owner gluster -j ACCEPT
    iptables -I OUTPUT -p tcp --dport 24007 --match owner --uid-owner root -j ACCEPT

To make this work, users primary group should be gluster. REST API authentication is not required if the Gluster CLI commands are executed in any one node of Cluster.

To use Gluster CLI from other nodes which are not part of the
Cluster(Can be a Windows/Mac machine!), can specify host, username and
password information.

Use Gluster CLI to create/modify user(Which will use REST API, but
these APIs are restricted to `localhost` usage)

    gluster useradd <USERNAME> <PASSWORD>
    gluster usermod <USERNAME> <NEW_PASSWORD>
    gluster userdel <USERNAME>

Now use Gluster CLI from anywhere(Make sure port 24007 is accessible
from that node)

    gluster -h <HOSTNAME> -u <USERNAME> [-p <PASSWORD>] ...

Password is optional, if not provided then it will prompt the
password.

## Backward incompatible changes

- XML Output will be deprecated in favor of JSON output
- Force option will be divided into multiple options to give more control
  for users
- Optional arguments should be prefixed with `--`. For example,
  `replica 2` will become `--replica 2` or `--replica=2`
- New error codes to differentiate the CLI output. For example,
  "Volume already started" exit with different error code so that
  consumer can safely ignore this error based on error code.
- Reorganized command names, For example `gluster geo-replication ...` instead of `gluster volume geo-replication ...`
- Reorganized subcommands, For example `geo-replicaton create <session>` instead of `geo-replicaton <session> create` to match the syntax similar to Gluster Volume commands `gluster volume create <volname>`

Started listing the syntax changes for all commands(One example added below). - In progress.

### Volume Operations

Volume Create (Existing and New):

    # Existing
    volume create <NEW-VOLNAME> [stripe <COUNT>] \
        [replica <COUNT> [arbiter <COUNT>]] \
        [disperse [<COUNT>]] [disperse-data <COUNT>] [redundancy <COUNT>] \
        [transport <tcp|rdma|tcp,rdma>] \
        <NEW-BRICK>?<vg_name>... \
        [force]

    # New
    volume create <NEW-VOLNAME> [--stripe <COUNT>] \
        [--replica <COUNT> [--arbiter <COUNT>]] \
        [--disperse [<COUNT>]] [--disperse-data <COUNT>] [--redundancy <COUNT>] \
        [--transport <tcp|rdma|tcp,rdma>] \
        [--allow-root-dirs] \
        [--reuse-bricks] \
        <NEW-BRICK>?<vg_name>...

**Comment by amarts** [comment]
This is good summary of what the new CLI would look like. 

Please share this URL link to devel mailing list, so any one who is consuming current CLI directly in their scripts, projects or product can be aware of the changes coming in future.

**Comment by amarts** [comment]
for sometime till we take down current `gluster` CLI, can we call it `gluster2` (like `python3` etc)

**Comment by purpleidea** [comment]
> XML Output will be deprecated in favor of JSON output

Cool! One quick question, why this change? Seems like an unnecessary difference.

**Comment by aravindavk** [comment]
> Cool! One quick question, why this change? Seems like an unnecessary difference.
XML output can be easily provided, but it is overkill to support old XML format(Existing output)

**Comment by purpleidea** [comment]
> it is overkill to support old XML format(Existing output)

Ah. I agree. I think the idea of a new format is good, but keeping this as XML. In that case the folks who depend on machine parseable output only have to fix the structure, but don't *also* have to switch from an XML parser to a json parser.

**Comment by aravindavk** [comment]
> Ah. I agree. I think the idea of a new format is good, but keeping this as XML. In that case the folks who depend on machine parseable output only have to fix the structure, but don't also have to switch from an XML parser to a json parser.

Makes sense. I will update it as XML format change

**Comment by aravindavk** [comment]
Comment https://github.com/gluster/glusterd2/issues/205#issuecomment-303060253 suggests that local requests(REST request comming from same machine) can skip the REST authentication but can be controlled via Port access. But now realized that no solid way to identify the local request.

https://golang.org/pkg/net/http/#Request This object has field for "Host", but this can be easily spoofed, for example

    curl -H 'Host: 127.0.0.1:24007' http://<hostname>:24007

Due to this issue, we can't skip Authentication even if requests coming from local node.

Any ideas to identify the hostname from where request is coming from?

**Comment by prashanthpai** [comment]
I know about [http.Request.RemoteAddr](https://golang.org/pkg/net/http/#Request) but I'm not sure if it can be spoofed/faked.

A crazy thought: can you do REST over unix domain socket ? I think you can as they support `SOCK_STREAM` which `HTTP` relies on. But I can't imagine how a client would send a request without URL.

**Comment by aravindavk** [comment]
> I know about http.Request.RemoteAddr but I'm not sure if it can be spoofed/faked. But this address is derived from underlying TCP connection, so it should be trustable.

Documentation says it is set by server, so should be fine to use this. Only extra work is to compare with its own list of IPs to check if the request is from local node.

> A crazy thought: can you do REST over unix domain socket ? I think you can as they support SOCK_STREAM which HTTP relies on. But I can't imagine how a client would send a request without URL.

With this only CLI can use REST APIs(Similar to glusterd1). RemoteAddr approach looks good.

**Comment by aravindavk** [comment]
## Backward compatibility:
Based on other developers and users feedback, we need to provide backward compatibility to existing CLI commands.

As part of that, I wrote a library which can be used to convert the incoming arguments of old format into new format. Rest of the parsing code in CLI will remain same.

In the main func of CLI, call `migrateArgs()` so that os.Args will have rearranged and converted to new format.

Code as below, Not yet handled all the situations but looks positive.

    package main
     
    import (
            "os"
            "fmt"
    )
     
    var newOptions = map[string]string {
            "force": "--force",
    }
     
    var newOptionsVolume = map[string]string {
            "replica": "--replica",
            "arbiter": "--arbiter",
            "disperse": "--disperse",
            "disperse-data": "--disperse-data",
            "redundancy": "--redundancy",
            "transport": "--transport",
    }
     
    var newOptionsGeorep = map[string]string {
            "ssh-port": "--ssh-port",
            "no-verify": "--no-verify",
            "push-pem": "--push-pem",
    }
     
    var georepCommands = map[string]bool {
            "create": true,
            "start": true,
            "stop": true,
            "delete": true,
            "pause": true,
            "status": true,
            "resume": true,
    }
     
    func argsMigrate(){
            var tmpArgs = []string{}
            for k, arg:= range os.Args{
            	if val, ok := newOptions[arg]; ok {
            		os.Args[k] = val
            	}
            }
     
            if len(os.Args) >= 3 && os.Args[1] == "volume" && os.Args[2] == "create"{
            	for k, arg:= range os.Args{
            		if val, ok := newOptionsVolume[arg]; ok {
            			os.Args[k] = val
            		}
            	}		
            }
     
            if len(os.Args) >= 3 && os.Args[1] == "volume" && os.Args[2] == "geo-replication"{
            	tmpArgs = []string{os.Args[0], os.Args[2]}
            	command := ""
            	for _, arg:= range os.Args{
            		if _, ok := georepCommands[arg]; ok {
            			command = arg
            		}
            	}
            	tmpArgs = append(tmpArgs, command)
            	for _, arg:= range os.Args[3:]{
            		if val, ok := newOptionsGeorep[arg]; ok {
            			arg = val
            		}
            		if arg != command && arg != "volume"{
            			tmpArgs = append(tmpArgs, arg)
            		}
            	}
            	os.Args = tmpArgs
            }
    }
     
    func main(){
            fmt.Println(os.Args)
            argsMigrate()
            fmt.Println(os.Args)
    }

Example output:

    $./gluster volume create gv1 replica 2 node1:/bricks/b1 node2:/bricks/b2 force
    Before [./gluster volume create gv1 replica 2 node1:/bricks/b1 node2:/bricks/b2 force]
    After  [./gluster volume create gv1 --replica 2 node1:/bricks/b1 node2:/bricks/b2 --force]
     
    $./gluster volume geo-replication gv1 node3::gv2 create force ssh-port 22
    Before [./gluster volume geo-replication gv1 node3::gv2 create force ssh-port 22]
    After  [./gluster geo-replication create gv1 node3::gv2 --force --ssh-port 22]

Let me know your thoughts.

**Comment by atinmu** [comment]
I believe this git hub issue was filed to track the CLI infrastructure changes which I believe is now completed. Can we please make sure for respective commands a different github issue is filed from now onwards and this issue can be closed?

**Comment by prashanthpai** [comment]
Make sense. Closing this.
