### ISSUE TITLE
Handle simultaneous peer add/delete requests

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#210]
When a glusterd instance concurrently receives add peer and/or delete peer, the current behaviour is undefined. And during add peer or delete peer, the transaction framework also isn't usable. We need some form of locking during peer operations which modify the node's cluster membership. The current etcd management code only takes locks for etcd start/restart.

**Comment by kshlm** [comment]
Probably just document this for Rouge one.

**Comment by atinmu** [comment]
@prashanthpai Is this issue still seen?

**Comment by prashanthpai** [comment]
@atinmu This changed after `elasticetcd` was introduced but I think the problem still exists.

**Comment by purpleidea** [comment]
On Tue, Nov 7, 2017 at 1:23 AM, Prashanth Pai <notifications@github.com> wrote:
>
> @atinmu This changed after elasticetcd was introduced but I think the problem still exists.

I had on my personal TODO list to clean up and make more portable to
mgmt etcd implementation. Would you like me to libify it for use in
gd2?

/cc @kshlm

**Comment by kshlm** [comment]
This package was the result of the refactor/rewrite attempt I did on the mgmt etcd package.
It works well, but probably misses out some of the corner cases that were handled in the mgmt etcd package.

**Comment by purpleidea** [comment]
On Tue, Nov 7, 2017 at 2:25 AM, Kaushal M <notifications@github.com> wrote:
>
> This package was the result of the refactor/rewrite attempt I did on the mgmt etcd package.
> It works well, but probably misses out some of the corner cases that were handled in the mgmt etcd package.

Okay, well after learning a lot more about etcd, I've realized it's
time for another rewrite-- if you'd like this for gd2, please say yes,
otherwise say no or ignore.

**Comment by kshlm** [comment]
I'm interested in having GD2 and mgmt share a common etcd package. It would benefit both of us.
But I'd like to have elasticetcd be the common package. As it is right now, it is a clean package without any external dependencies other than etcd itself, and the logrus package. It would be very easy to move the package into a seperate repository if required.

I'd like it if you can check out the package and see it for yourself. If you'd still prefer to (re)write a different package, I will not be interested in importing that package for GD2.

**Comment by obnoxxx** [comment]
@kshlm writes:
> I'm interested in having GD2 and mgmt share a common etcd package. It would benefit both of us.

That seems like a promising start.

> But I'd like to have elasticetcd be the common package.

OK. For what reason? NIH or technical reasons? ... ;-)

> As it is right now, it is a clean package without any external dependencies other than etcd itself, and the logrus package. It would be very easy to move the package into a seperate repository if required.

Afaict, this applies more or less to the mgmt implementation as well. We should be a little more specific.

> I'd like it if you can check out the package and see it for yourself. If you'd still prefer to (re)write a different package, I will not be interested in importing that package for GD2.

It is really irritating how everyone keeps insisting on his code and refuses to even consider using the other project's code. Rather start a re-implementation of something that exists than using and improving it. My way or the highway... It would really be good if we could stop this kindergarden behavior.

My understanding is that the elasticetcd pkg was created after looking at @purpleidea 's implementation in mgmt (note: NIH, create a new lib instead of working on improving the existing implementation). But now James states that he has spotted problems in both implementations and suggests we need a "rewrite":

> My understanding was that both this one, and mine, were in need of a re-write. 
> Okay, well after learning a lot more about etcd, I've realized it's time for another rewrite

First of all, it would be helpful to learn in more detail what are the problems that you spotted, @purpleidea.  ==> Please elaborate!

Secondly, I hope that with "rewrite" you actually do not necessarily mean starting a new one from scratch. IMHO, this is *almost always* a bad idea! If both implementations have issues, and it should or could be externalized, then we should create that external project and move towards that is good and complete and fixes the problems. It should not matter off of which code base we actually start. @purpleidea , could you elaborate on how you would approach such a "rewrite"? 

@kshlm it's also a question of how far your statement goes. If someone goes and refactors the elasticetcd implementation to fix significant issues, and assume after the work, many places don't resemble the original code drop any more, would you also not be willing to consider this? Or only based on who did the changes?...

This is a really important topic, also for the potential future integration of higher level disk and volume management logic (as coming from heketi), which will rely heavily on a consistent, race-free, corruption-free state store. We will need that. And I don't really too much about who does the changes, or how the project is named, etc. But that it get's done and these serious issues are addressed.

My few cents...

cc @raghavendra-talur

**Comment by purpleidea** [comment]
On Thu, Nov 9, 2017 at 7:27 AM, Michael Adam <notifications@github.com> wrote:
> First of all, it would be helpful to learn in more detail what are the problems that you spotted, @purpleidea. ==> Please elaborate!

This is a fair and good question. Here is a bit of background and some
details. Over a year or so ago, I wrote the initial embedded etcd
implementation. This happened before etcd even supported this more
easily through the embed package. I even helped contribute to the
current embed proposal with an initial prototype.

I had written my mgmt etcd code against the V2 API. I quickly realized
there were some limitations I wanted to avoid and re-wrote it against
V3.

It was good enough to get me this far, but still has some limitations.
Now that my golang and etcd internals knowledge is much better, and
I'm optimistic about trying to fix this once and for all.

Here are some of the issues that exist in either one or both of the
embedded etcd implementations:

* Timer based delays instead of event based delays. I'd like to remove
all instances where we call a `time.Sleep` that aren't critically
necessary.

* Race-Free quorum/election changes. During rapid cluster fluctuations
or in "special case" scenarios (eg: 2 host clusters) there are
situations where the code can deadlock or perform in a way that isn't
ideal. I think the former is more likely true for mgmt, and the latter
more true for gd2. I've seen some two host cluster issues in gd2 and
multiple simultaneous joins or parts in mgmt can be an issue. In
engineering scenarios these don't tend to cause a problem, but they
will be a show-stopper for customers that want to use this in
production.

* Clean API that can be effectively re-used. It's silly that inside
Red Hat we've developed two different etcd embedding libraries. I
guess we like this sort of thing (GlusterFS vs Ceph, Puppet vs.
Ansible, etc...) Nevertheless, I think it's worth spending some time
properly refactoring the internal etcd package so that it can be
properly used as a library without any mgmt or gd2 specific ties.
Naturally both code bases would probably have some add ons for their
own specific use cases.

* Rebase against upcoming etcd 3.3. There is some additional
functionality in the most recent etcd releases (and upcoming release)
which can simplify and improve our code. I'd like to get rid of some
technical debt in the libraries and bring this up to date.

* Handle reconnections silently. At least in mgmt, reconnections
aren't as transparent as I'd like and they can generate additional
events. I think I can fix this problem properly.

There are some other issues in both of the code bases but I don't
think I need to mention them further. I think I've got a lot of etcd
and golang experience and am in a good position to use what I've
learned to re-write this code. I don't plan on using either mgmt or
gd2's code base as an initial start, but rather I plan to read through
both code bases and write a new package "from scratch". My second step
will be to port the library to gd2 and to mgmt.

Lastly, I'd definitely appreciate any comments and tips from the gd2
team about outstanding issues or features they'd like to see in the
library so that I can incorporate these requirements if possible.

Hopefully you like this proposal, and it will give you more time to
focus on the more important parts of gd2, and leave the etcd issues to
me.

Thanks for your consideration.

**Comment by kshlm** [comment]
@obnoxxx @purpleidea I realise I should have worded what I wrote better. I'll try to clarify my reasons better.

### Why did I create elasticetcd?

It was not NIH.

I did initially start out trying to use the the etcd implementation, and that was main reason I became interested in mgmt in the first place. @purpleidea helped out by separating out the implementation into a new package as well.

But the package created was a combined package that implemented the elastic algorithm and mgmt specific etcd functions. There wasn't (and there still isn't) a way to just import the elastic algorithm part from the package.

I began refactoring the package to split into two, one with the algorithm only and the other with the mgmt etcd specific stuff. 
During this refactor, I found that etcd had some new features with its v3 API (eg. sessions, watches) that would help make it easier to implement the algorithm. The elastic algorithm implemented in mgmt was based around the features available with etcd v2 API, and was not as clean as it could be.

I used the new api and features, and rewrote the algorithm around them. This effectively made the algorithm package a new implementation, rather than a refactor of the earlier combined package.

The elasticetcd package was the end result. It is a clean, reusable package that just implements the elastic algorithm, without any GD2 specific functions or dependencies.

The GD2 specific functionality is implemented in a different GD2 store package, that uses the elasticetcd package.

I'll concede that I did not effectively communicate back about the new package, with @purpleidea and the mgmt community. If I had done this right, I believe we wouldn't be having this conversation, and instead be collaborating on a common package already.

### Why should we collaborate around elasticetcd?

For the reasons mentioned above, it is much easier to work with elasticetcd, instead of mgmt's etcd package. I'll repeat again, elasticetcd does not have any dependencies on GD2. It was designed to be a reusable package. This makes it easier to move it into its own repository and collaborate on, instead of trying to split out the etcd package from mgmt.

That doesn't matter, as @purpleidea intends to write a new package. I am against this, as I believe it will be beneficial to the both of us, to work on elasticetcd, or start from it as the base.

As per the proposal, the package he intends to create is what elasticetcd already is. Elasticetcd makes use of the newer etcd APIs, uses events/watches, and has a reusable API. There are issues that need to be solved though, but those are among the issues to solved mentioned in the proposal as well (2-node, rapid changes to cluster...). We would save a lot of time if we solved these problems in elasticetcd, instead of trying to start from scratch again.

I'm happy to move the elasticetcd package out of the GD2 repo to make collaboration easier. I'm okay with elasticetcd being refactored heavily if required as well. As long as the exposed API remains same (or similar) , GD2 doesn't care how elasticetcd works internally.

But if a new package was created, I'm not set against using it. It wouldn't be a lot of work to update the GD2 store package to use the new package. But only if I can be convinced that it is the better choice.

So, @purpleidea I strongly believe you should reconsider starting from scratch. Hopefully, as you explore elasticetcd, you will come to believe the same. Let me know, if you need more help convincing.

**Comment by obnoxxx** [comment]
Thanks @kshlm and @purpleidea for your explanations. Curious where we go from here...

**Comment by obnoxxx** [comment]
Has anything happened yet?

I.e. is there any kind of conclusion how a shared etcd lib would look like?
Would it be an advancement of the elasticetcd package, or of the mgmt lib,
or would it be an entirely new package?

Any code anywhere? @purpleidea @kshlm 

Thanks - Michael
