### ISSUE TITLE
Easy pluggability/flexibility to support an future volume type 

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#269]

**Comment by amarts** [comment]
Some time back I had discussion with @kshlm and @prashanthpai about an easier and flexible option to create volume files.

Let glusterd2 provide templates, and not restrict anything regarding placement of translator in graph (an exception can be for all entry (fuse, protocol/server, nfs) and leaf-node (protocol/client, posix) xlators).

Proposal is to keep the template simple with barebone skeleton volfile with just the relations, and glusterd automatically fills all the options with default options.

For example a template would look like below yml file.

```
<volume-name>-<brick-path>.vol : <template-name>.brick.template
trusted.<volume-name>.<transport>.fuse.vol : trusted.<template-name>-<transport>.fuse.template
<volume-name>.<transport>.fuse.vol : <template-name>-<transport>.fuse.template
<volume-name>.gfproxy.vol : <template-name>.gfproxy.template
<volume-name>.rebalance.vol : <template-name>.rebalance.template
```
Now an example template would look like below for an gfproxy.vol

```
volume <volume-name>-client-<brick-index>
    type protocol/client
end-volume

volume <volume-name>-replicate-<replica-pair-index>
   type cluster/replicate
   subvolumes [<volume-name>-client-<brick-index>]
end-volume

volume <volume-name>-distribute-<distribute-index>
  type cluster/distribute
  subvolumes [<volume-name>-replicate-<replica-pairs>]
end-volume

volume <volume-name>-server
   type protocol/server
   subvolumes <volume-name>-distribute-<distribute-index>
end-volume
```

With the above (or similar) approach:
* we can keep the translator placement easier for managing.
* no code changes required for testing new xlators.
* can create different volume files with different names and consume it separately later.
* For validating supportability, as go would be statically compiled, we can have encrypted templates which would be supported, and allow users to create new templates if required.

The challenges with this approach is how to handle enabling and disabling of translators itself  using volume set.  As of now, I would bring a global option 'option enabled yes' or 'option enabled no' for all the translators, and manage the graph management inside libglusterfs itself while loading volume files.

This I guess would be quicker to implement, and also would provide lot of flexibility for user to create their own templates.

Comments welcome.

**Comment by aravindavk** [comment]
Since `glusterd2` will provide configuration store for all components
which are not dependent on volfiles. Following approach will provide
single infrastructure for both volfile generation and configuration
management for other components.

Each Xlator or Gluster component exposes a YML file which will have
details about all the options, help messages and default values.

Glusterd2 will parse these files on startup or on receiving a specific
signal and prepares options dictionary.

When user changes the options, values will be stored in `etcd`

Example Xlator file

    name: $volume-changelog
    type: features/changelog
    enabled: false
    options:
      - name: changelog-barrier-timeout
        help: Set Barrier Timeout
        value: 120
        type: numeric
        min: 10
        max: 240
        validation: minmax
     
      - name: changelog-dir
        help: Changelogs directory
        value: $brick/.glusterfs/changelogs
        validation: path
     
      - name: changelog-brick
        help:
        value: $brick
        tunable: false

Similarly non-xlator component like Geo-rep can expose similar YML file.

    name: georep
    type: features/georep
    enabled: false
    options:
      - name: sync-jobs
        help: Number of Sync Jobs
        value: 3
        type: numeric
        min: 1
        max: 100
        validation: minmax
     
      - name: log-level
        help: Log Level
        value: INFO
        allowed_values: [INFO, DEBUG, ERROR]
        validation: allowed_values

volfile can be generated using a seperate template for each volfile.
For example bricks volfile template,

    posix
    trash
    changetimerecorder
    changelog
    bitrot-stub
    access-control
    locks
    worm
    read-only
    leases
    upcall
    io-threads
    marker
    barrier
    index
    quota
    io-stats
    server

During volfile generation, Glusterd2 uses the above default values
published by Xlator and substitutes the user overridden values and
generates the Volfile as below(Only one snippet in Volfile)

    volume gv1-changelog
        type features/changelog
        option changelog-barrier-timeout 120
        option changelog-dir /bricks/b1/.glusterfs/changelogs
        option changelog-brick /bricks/b1
        subvolumes gv1-changetimerecorder
    end-volume

Note: "subvolumes gv1-changetimerecorder" is based on the next
subvolume mentioned in the template file.

Advantageous with this method:

- Default values and help messages stays with Xlator/Component, easy
  for developers while adding new options or to change help messages
  or to update default values.
- Overridden values are stored in glusterd2(etcd).
- Generated volfiles can be cached in etcd itself, to avoid template
  lookups everytime.
- Same infrastructure can be used for other components to provide
  config store.
- Options validation is easy

Let me know your inputs.

**Comment by amarts** [comment]
I am fine with xlators giving options in yml file, in the above format.  If everyone agrees, we should make it a default. But, notice that it involves code change in glusterfs's xlators, as today its all in an structure, and also 'reconfigure()' also happens inside xlator code, instead of glusterd.  Check how this would work.  :+1 from me on changing toward this approach.

Btw, above is outside of how the 'graph' looks.  I would change your idea a bit by giving the xlator list as exact 'type' instead of just the basename (there can be conflicts).

**Comment by kshlm** [comment]
@aravindavk This is pretty much what we want. The prototype I was working on at kshlm/glusterd2-volgen already has the code for xlator files, which can be reused if required.

There are a few things I'd like to add,
1. Use `<xlator-id>.<option>` as the key for volume set, and ensure that each xlator has a unique id. This is mainly to prevent the same key being applicable to multiple xlators, for eg. performance.cache-size which sets the cache-size for a lot of perf xlators. 

2. Instead of having a simple text file with a list of xlators, it would be nice if the template file was a structured file as well (yaml, toml etc...). For eg.,
```yml
name: brick
root-xlator: protocol/server
xlators:
  - name: protocol/server
    subvolumes: debug/io-stats
  - name: debug/io-stats
    subvolumes: features/quota
# and so on
```
This will allow us to define graphs which asymmetric graphs like those for tiering, snapd, jbr etc. 

3. We should also think about ways to deprecate and retire options. The op-version framework we have is a start, but isn't a full solution.

4. Have a method to either generate the xlator options C code automatically for each xlator from the xlator file (or the vice-versa). This should help keep duplication of the options table to a minimum.

**Comment by atinmu** [comment]
@aravindavk Where are we w.r.t feature completion? Please label this issue accordingly.

**Comment by aravindavk** [comment]
Current volgen handles all the volume types and options. Template based volfiles generation is low priority. Closing this issue.
