### ISSUE TITLE
gluster volume status should display size of the volume

### ISSUE THREAD

**Issue by atinmu** [gluster/glusterd2#329]
It'd be good to display the total size and current utilization of the volume in volume status output.

**Comment by shtripat** [comment]
@atinmu I would suggest to have volume level aggregations like client_connections, georep details, rebalance details and snapshot related details as well (at least on one of the nodes which work as etcd server as well). 

I am bringing this from the tendrl's view of consumption. Currently tendrl does lot of these kind aggregations which ideally should be done inside gluster (gd2 in this case) and tendrl kind of consumers should rather just use these details.

I would like to have comments/suggestion from others as well here.

**Comment by aravindavk** [comment]
We can collect the statvfs info from each bricks and aggregate the results to Volume level.  Aggregation logic for an distributed replicate volume 2x2

    Total Size = min (total_size of b1, total_size of b2) + min(total_size of b3, total_size of b4)
    Total Free = min (total_free of b1, total_free of b2) + min(total_free of b3, total_free of b4)

If a node is down, then result will not be accurate. We can add similar aggregation logic for other Volume types.

Only known issue is if multiple bricks in same root partition, then the values will be wrong(We can follow the approach as in https://review.gluster.org/#/c/17618/)

If this issue is priority, I can start working on it.

**Comment by atinmu** [comment]
@aravindavk I don't think collecting stats from individual bricks and then aggregating it at volume level would be ideal. Instead we should try to get the statvfs executed from a temp mount point of the volume and rely on gluster's fs xlators to provide those details. Priority of this issue should be low for now. IMO, we can target this in 4.1.
