### ISSUE TITLE
Explore using etcd v3 transactions

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#527]
More details [here](https://coreos.com/blog/transactional-memory-with-etcd3.html)

**Comment by purpleidea** [comment]
I'm pretty familiar with etcdv3 transactions, so happy to help if anyone has any questions.
In particular it's interesting to note that you can also have nested transactions.
Use all of these in moderation since running them blocks-the-world.
I forget if the nested ones are in a release or not yet. I can check if need be.

**Comment by kshlm** [comment]
@prashanthpai implemented bits of this to perform txn context storage operations during transactions with #809.

**Comment by prashanthpai** [comment]
#809 uses etcd v3 transactions to PUT multiple key-value pairs as a single atomic operation. We may continue to use etcd v3 transaction wherever we see fit, probably in the new/better txn framework https://github.com/gluster/glusterd2/issues/919

There's nothing else to be done here. Closing this issue
