### ISSUE TITLE
Not able to create brick directory  Automatically while creating volume

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#675]
desc:
"./glustercli volume create"  command not able to create brick directory automatically while creating volume.

"./glustercli volume create vol3 10.70.35.52:/bricks/brick0/abc 10.70.35.137:/bricks/brick0/abc 10.70.35.79:/bricks/brick0/abc "
mount point : /bricks/brick0
directory : abc
In the above command "abc" directory has to be created manually, otherwise "volume create" command failing with below error.
Error:
Volume creation failed

Error: Request failed with HTTP Status code 500
no such file or directory

**Comment by obnoxxx** [comment]
I don't fully understand this yet: The volume create cli (in this basic form) is given brick paths. These paths should exist. What in the above request would trigger gluster to create the directory? Just that it's named `abc` instead of `brick` or `brick0`? So if the command instead was
```
./glustercli volume create vol3 vol3 10.70.35.52:/bricks/brick0 10.70.35.137:/bricks/brick0 10.70.35.79:/bricks/brick0
```
would you then require it to create `brick0`? Or if the command was
```
./glustercli volume create vol3 vol3 10.70.35.52:/bricks/abc 10.70.35.137:/bricks/abc 10.70.35.79:/bricks/abc
``` 
would the answer be any different? Etc... So mainly I'm saying, I don't see based on what data should gd2 decide to create a directory. But it might as well be that I lack some context. At least this would match perfectly with current gluster/gd1, which expects the brick dir to exist.

**Comment by rmadaka** [comment]
Gd1 volume create command:

 gluster volume create vol1 10.70.35.118:/bricks/brick0/vol1 10.70.35.128:/bricks/brick0/vol1 10.70.35.53:/bricks/brick0/vol1 
volume create: vol1: success: please start the volume to access data

In above command /bricks/brick0 is a mount point  which is already exist, i didn't create vol1 dir manually , at the time of volume creation vol1 dir created automatically.

vol info:
gluster vol info vol1
 
Volume Name: vol1
Type: Distribute
Volume ID: 226b4338-13fc-47fd-b15e-ca3aad7f61fc
Status: Started
Snapshot Count: 0
Number of Bricks: 3
Transport-type: tcp
Bricks:
Brick1: 10.70.35.118:/bricks/brick0/vol1
Brick2: 10.70.35.128:/bricks/brick0/vol1
Brick3: 10.70.35.53:/bricks/brick0/vol1
Options Reconfigured:
transport.address-family: inet
nfs.disable: on
cluster.server-quorum-ratio: 90

**Comment by prashanthpai** [comment]
@rmadaka Please take the new build from me.

**Comment by aravindavk** [comment]
> @rmadaka Please take the new build from me.

Please build using `PREFIX=/usr make` so that defaults will match the QE setup
