### ISSUE TITLE
Hostnames (non-IP) must work for all peer communication

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#725]
When a user specifies a hostname for a peer, it should persist through-out the system

**Comment by obnoxxx** [comment]
@jarrpa

This will be important for the future, how we run gluster specifically in the container space. The background requirement is: Will it be possible to have gluster nodes changing IP addresses when rebooted (dhcp etc), and still remain part of the cluster because peer-probe had been done with a hostname that will remain associated to this node even when the IP changes?

**Comment by aravindavk** [comment]
> When a user specifies a hostname for a peer, it should persist through-out the system

Is this issue about the first node? which is not added via peer probe, Glusterd2 itself will detect the IP/hostname on start.

**Comment by prashanthpai** [comment]
> Is this issue about the first node? which is not added via peer probe, Glusterd2 itself will detect the IP/hostname on start.

This is about peer attach requests. If a user specifies a hostname during peer attach, it should work and the hostname should appear (instead of IP) everywhere. IOW, we shouldn't implicitly convert hostname to IP internally when we store it in etcd.

**Comment by aravindavk** [comment]
I also observed that, by default we are adding Host IP as peer address while adding self details on Glusterd2 start(`glusterd2/config.go`). We should change this to update hostname itself if peeraddress is not specified in config.
