### ISSUE TITLE
Issues with REST authentication by default for local clients

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#994]
Clients on the same machine should be able to talk to local glusterd2 by default unless configured otherwise. IMO, we turned on rest API authentication on by default a little too early in the development stage.

If the above isn't feasible or proper, at least we need the following:

1. The CLI option `auth` should have some sane default which points to default location of authfile
2. Document the auth file usage in quick start guide

Another problem (and with point 1) is that the auth file has root permissions (which is correct) as its generated by glusterd2. However, glustercli can't readily read that file when it's run as non root user.

```sh
$ glustercli --authfile /tmp/gd2_func_test/w1/auth peer list
failed to read secret

Error: open /tmp/gd2_func_test/w1/auth: permission denied
```

glustercli should be able to run as any user. So, I propose:

* Instead of an "authfile", the CLI can simply take the token as input
* CLI should be able to read an environment variable (say `GLUSTERD2_AUTH_TOKEN`) which has token. This is a convention followed very widely in many projects

**Comment by prashanthpai** [comment]
**cc** @aravindavk

**Comment by prashanthpai** [comment]
```toml
$ cat glusterd2.toml.example
localstatedir = "/var/lib/glusterd"
peeraddress = ":24008"
clientaddress = ":24007"
#restauth should be set to false to disable REST authentication in glusterd2
#restauth = false
```

If it's turned on by default, the example file should show the default value which is `true`

**Comment by aravindavk** [comment]
> Clients on the same machine should be able to talk to local glusterd2 by default unless configured otherwise. IMO, we turned on rest API authentication on by default a little too early in the development stage.

CLI auth file path defaulted to match with the file where glusterd2 looks for it by default. `glustercli` will work without any changes with standard deployment.

> Another problem (and with point 1) is that the auth file has root permissions (which is correct) as its generated by glusterd2. However, glustercli can't readily read that file when it's run as non root user.

This is intentional, if "gluster" group exists in machine, auth file can be read by any users who belong to "gluster" group. In this case, auth file is created as "root" user since "gluster" group doesn't exist. I agree we need to document this behavior.

> Instead of an "authfile", the CLI can simply take the token as input

`--secret` option is also available with glustercli.

Usecase for authfile: Accepting token/secret directly as in CLI is not safe since other people can see the secret. Without authfile it is very difficult to control which all users can access `glustercli` within cluster.

> CLI should be able to read an environment variable (say GLUSTERD2_AUTH_TOKEN) which has token. This is a convention followed very widely in many projects

+1, this method can be used as alternative to `--secret` option. But authfile support is required for above mentioned reasons.

**Comment by phlogistonjohn** [comment]
+1 on the environment variable approach. its both invisible to casual shoulder surfing and easy to set up.
I would just ask the names be somewhat consistent. If the cli option is --secret the env var should be more like GLUSTERD2_AUTH_SECRET  (perhaps GLUSTER_CLI_SECRET is even better). I would also allow the env var equivalent to --user for completeness and parity with what heketi-cli supports.
